### ISSUE TITLE
Firefox adaptation

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/msdn-delocalizer#11]
Unlike Chrome, Firefox now lacks of proper plugin to delocalize MSDN (the one I've found lacks source code link which couldn't be good), so after 2 user requests I've decided we'll need a Firefox plugin, too.

**Comment by 62mkv** [comment]
shouldn't FF currently support most Chrome plugins as-is (or with just a minimal repackaging)? there was big hype when they moved away from XUL for plugins and they explained that now FF plugin ecosystem is compatible with Chrome?

**Comment by ForNeVeR** [comment]
I've no idea about that. If someone wants to give it a try and install from Chrome web store into FF, they're welcome.
